### ISSUE TITLE
Queued videos not autoplaying if tab isn't focused in Chrome

### ISSUE THREAD

**Issue by Stromwerk** [boramalper/Essential-YouTube#2]
**Steps to reproduce**
1. Add some videos to the queue (like [this](/http://essentialyoutube.com/#xBT3FbAlZfE), or [this](/http://essentialyoutube.com/#5bIbriC-Vgk)) then play the first video. 
2. Now if you don't want to wait just skip to 5-10 seconds before the end of the video and switch your tab so that the Essentialyoutube tab isn't focused.
3. If you look at the Essentialyoutube tab, it's name changes, because the next video loads, however it doesn't start playing automatically.

**Browser information**
- **User agent** : Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
- **Browser version**: Google Chrome Version 51.0.2704.106 m (64-bit)

**Comment by Stricted** [comment]
"If you look at the Essentialyoutube tab, it's name changes, because the next video loads, however it doesn't start playing automatically."

go on youtube, right click on a video and open it in a new tab, if the tab is not focused the video is not playing - thats a general chrome problem ;)

**Comment by Stromwerk** [comment]
I guessed as much, because I've seen it also happen in youtube, but wasn't sure and decided to open the issue. Feel free to close the issue :)

**Comment by boramalper** [comment]
> go on youtube, right click on a video and open it in a new tab, if the tab is not focused the video is not playing - thats a general chrome problem ;)

Oh, I was not even aware of that! I'm closing the issue then, as there is nothing to be done on our side. Feel free to open another issue if you have a solution or workaround.
